{"title": "Liverpool 0-1 Aston Villa: Đội khách bất ngờ dẫn trước", "des": "Liverpool chơi áp đảo, nhưng lại để đối thủ mở tỷ số sau một pha triển khai bóng nhanh ở phút 44.", "href": "/liverpool-0-1-aston-villa-doi-khach-bat-ngo-dan-truoc-post1203010.html"}
{"title": "El Clasico cuối cùng của dàn huyền thoại", "des": "El Clasico không còn sức hút mạnh mẽ như xưa. Đó là cảm giác có thật trong lòng người hâm mộ từ khi dàn sao Barca không còn ở đó, và Galacticos của Real mất đi sự lấp lánh vốn có.", "href": "/el-clasico-cuoi-cung-cua-dan-huyen-thoai-post1202931.html"}
{"title": "Cầu thủ CLB Quảng Ninh được thưởng thêm 1,5 tỷ đồng", "des": "Chiều 10/4, các cầu thủ Quảng Ninh nhận thêm nguồn khích lệ trước trận gặp CLB Hà Nội ở vòng 9 V.League.", "href": "/cau-thu-clb-quang-ninh-duoc-thuong-them-1-5-ty-dong-post1202972.html"}
{"title": "Man City 1-2 Leeds: Cơn địa chấn tại Etihad", "des": "10 người của Leeds đánh bại Man City ở trận đấu thuộc vòng 31 Premier League tối 10/4.", "href": "/man-city-1-2-leeds-con-dia-chan-tai-etihad-post1202971.html"}
{"title": "Kane ra điều kiện để ở lại Tottenham", "des": "Trong trường hợp Harry Kane chia tay Tottenham, Man Utd và Man City là 2 bến đỗ tiềm năng cho thủ quân tuyển Anh.", "href": "/kane-ra-dieu-kien-de-o-lai-tottenham-post1202946.html"}
{"title": "Dương Hồng Sơn làm huấn luyện viên đội Quảng Nam", "des": "Cựu thủ môn tuyển Việt Nam sẽ thay HLV Nguyễn Thành Công nhằm cải thiện thành tích của nhà vô địch V.League 2017 ở giải hạng Nhất.", "href": "/duong-hong-son-lam-huan-luyen-vien-doi-quang-nam-post1202918.html"}
{"title": "Ngoại binh CLB TP.HCM ghi bàn nhờ kế khích tướng của HLV Polking", "des": "CLB TP.HCM chi không dưới 1 triệu USD để mua 3 tiền đạo Brazil, nhưng phải đến trận đấu thứ 8, người hâm mộ mới phần nào nhìn thấy giá trị những ngôi sao này.", "href": "/ngoai-binh-clb-tphcm-ghi-ban-nho-ke-khich-tuong-cua-hlv-polking-post1202818.html"}
{"title": "Các cầu thủ CLB Quảng Ninh đua vô địch dù bị nợ lương", "des": "Bị nợ lương từ tháng 9/2020, các cầu thủ CLB Quảng Ninh vẫn giúp đội nhà vào nhóm dẫn đầu V.League, thậm chí đứng trước cơ hội vô địch ở mùa này.", "href": "/cac-cau-thu-clb-quang-ninh-dua-vo-dich-du-bi-no-luong-post1202889.html"}
{"title": "Có thêm 4,5 tỷ đồng, cầu thủ CLB Quảng Ninh vẫn ra sân gặp Hà Nội", "des": "Khúc mắc giữa ban lãnh đạo CLB Quảng Ninh với các cầu thủ về cơ bản đã được giải quyết trước trận đấu vòng 9 V.League 2021.", "href": "/co-them-4-5-ty-dong-cau-thu-clb-quang-ninh-van-ra-san-gap-ha-noi-post1202872.html"}
{"title": "Tuấn Anh trở lại tập luyện", "des": "Trở về Pleiku sau nhiều ngày ở Hà Nội để điều trị chấn thương và ăn đám hỏi Xuân Trường, tiền vệ Nguyễn Tuấn Anh đã ra sân tập cùng HAGL.", "href": "/tuan-anh-tro-lai-tap-luyen-post1202873.html"}
{"title": "Dương Thanh Hào: 'Tôi cũng phải nuôi con chứ'", "des": "Cựu trung vệ CLB Quảng Ninh cho biết anh rơi vào tình cảnh khó xử khi bị nợ lương sau ngày chia tay đội bóng đất mỏ.", "href": "/duong-thanh-hao-toi-cung-phai-nuoi-con-chu-post1202847.html"}
{"title": "Cầu thủ CLB Quảng Ninh sẵn sàng giải tán", "des": "Nếu vẫn không được giải quyết tình trạng bị nợ lương, lót tay trong ngày 10/4, các cầu thủ CLB Quảng Ninh sẵn sàng không làm nhiệm vụ tại vòng 9 V.League như tuyên bố.", "href": "/cau-thu-clb-quang-ninh-san-sang-giai-tan-post1202817.html"}
{"title": "Nhiều CLB muốn chiêu mộ Aguero", "des": "Leeds United là đội bóng mới nhất sẵn sàng gia nhập cuộc đua giành chữ ký của Sergio Aguero trong mùa hè 2021.", "href": "/nhieu-clb-muon-chieu-mo-aguero-post1202933.html"}
{"title": "Vì sao Zeros liên tiếp phạm sai lầm?", "des": "Zeros tự hủy hoại sự nghiệp vì hàng loạt bê bối ồn ào. Thế nhưng, đội chủ quản cũng không tránh được trách nhiệm sau sự cố của ngôi sao 21 tuổi.", "href": "/vi-sao-zeros-lien-tiep-pham-sai-lam-post1202173.html"}
{"title": "Kỷ lục của Messi, Ramos ở Siêu kinh điển", "des": "Những kỷ lục của Lionel Messi, Karim Benzema và Sergio Ramos được tính trong khuôn khổ trận Siêu kinh điển tại La Liga.", "href": "/ky-luc-cua-messi-ramos-o-sieu-kinh-dien-post1202909.html"}
{"title": "Man United quá tốt so với Tottenham", "des": "Khi Tottenham Hotspur nhấn chìm Man United ngay tại Old Trafford với tỷ số 6-1 vào tháng 10/2020, Jose Mourinho gọi đó là \"ngày lịch sử\" của câu lạc bộ.", "href": "/man-united-qua-tot-so-voi-tottenham-post1202890.html"}
{"title": "Siêu kinh điển cuối cùng của Messi?", "des": "18 tuổi, Lionel Messi bắt đầu được hít thở bầu không khí của trận gặp Real Madrid. Đêm nay, Leo lại ra sân nhưng với cảm giác rất khác.", "href": "/sieu-kinh-dien-cuoi-cung-cua-messi-post1202842.html"}
{"title": "Dấu chấm hết cho Griezmann ở Siêu kinh điển?", "des": "Antoine Griezmann là một cầu thủ giỏi. Nhưng ở Barca, tiền đạo người Pháp không quá đặc biệt tới mức CLB phải cần anh trong mọi trận đấu.", "href": "/dau-cham-het-cho-griezmann-o-sieu-kinh-dien-post1202811.html"}
{"title": "'Messi và Ronaldo có cùng một lý tưởng'", "des": "Trước trận El Clasico, Andrea Orlandi, cựu tiền vệ Barca chia sẻ với Goal về những kỷ niệm khi anh tập cùng siêu sao Lionel Messi.", "href": "/messi-va-ronaldo-co-cung-mot-ly-tuong-post1202801.html"}
{"title": "Bi kịch của người làm thay đổi lịch sử Chelsea", "des": "Một ngày của năm 2016, Jesper Gronkjaer, cựu cầu thủ Atletico và Chelsea, bắt đầu nhận thấy những dấu hiệu bất thường trong cơ thể.", "href": "/bi-kich-cua-nguoi-lam-thay-doi-lich-su-chelsea-post1202767.html"}
{"title": "Vì sao tỉnh Quảng Ninh không thể giải cứu cầu thủ bị nợ lương?", "des": "Khi bóng đá đi lên chuyên nghiệp, các câu lạc bộ hoạt động độc lập và không còn nằm trong sự kiểm soát của địa phương.", "href": "/vi-sao-tinh-quang-ninh-khong-the-giai-cuu-cau-thu-bi-no-luong-post1202807.html"}
{"title": "Cuộc đấu kinh điển Messi và Benzema", "des": "Trận đại chiến rạng sáng 11/4 (giờ Hà Nội) có thể là lần cuối cùng Lionel Messi và Karim Benzema so tài ở Siêu kinh điển.", "href": "/cuoc-dau-kinh-dien-messi-va-benzema-post1202764.html"}
{"title": "PSG thuyết phục Mbappe ký hợp đồng dài hạn", "des": "Gã nhà giàu nước Pháp quyết tâm giữ chân ngôi sao Kylian Mbappe trước sự nhòm ngó của các ông lớn châu Âu, đặc biệt là Real Madrid.", "href": "/psg-thuyet-phuc-mbappe-ky-hop-dong-dai-han-post1202805.html"}
{"title": "Zidane: 'Tôi mong Messi ở lại Barca'", "des": "Thuyền trưởng của Real Madrid tin việc Messi ở lại Barca sẽ mang hiệu ứng tích cực tới cho cả La Liga.", "href": "/zidane-toi-mong-messi-o-lai-barca-post1202799.html"}
{"title": "Hiệp hội eSports lên tiếng khi Zeros bị cấm thi đấu vĩnh viễn", "des": "Theo VIRESA (Hiệp hội Thể thao Điện tử Giải trí Việt Nam), án cấm thi đấu vĩnh viễn ở giải Liên Minh Huyền Thoại Việt Nam của tuyển thủ Phạm \"Zeros\" Minh Lộc vẫn được xem xét lại.", "href": "/hiep-hoi-esports-len-tieng-khi-zeros-bi-cam-thi-dau-vinh-vien-post1202791.html"}
{"title": "Real quật ngã Barca, MU đòi nợ Tottenham?", "des": "La Liga và Premier League sẽ cực kỳ sôi động với những trận cầu rất đáng được chờ đợi. Ở đó, Real Madrid chạm trán Barcelona, trong khi Tottenham đại chiến Man United.", "href": "/real-quat-nga-barca-mu-doi-no-tottenham-post1202571.html"}
{"title": "Luật FIFA cho phép cầu thủ Quảng Ninh được hủy hợp đồng", "des": "Luật của FIFA xác nhận các cầu thủ Quảng Ninh đã có thừa lý do để hủy hợp đồng với đội bóng chủ quản, vấn đề giờ chỉ nằm ở văn bản.", "href": "/luat-fifa-cho-phep-cau-thu-quang-ninh-duoc-huy-hop-dong-post1202806.html"}
{"title": "Mourinho làm gián đoạn cuộc họp báo để tri ân Hoàng thân Philip", "des": "Trong buổi họp báo trước trận Tottenham gặp Man Utd, HLV Jose Mourinho gửi lời chia buồn đến gia đình hoàng gia sau khi Hoàng thân Philip qua đời.", "href": "/mourinho-lam-gian-doan-cuoc-hop-bao-de-tri-an-hoang-than-philip-post1202754.html"}
{"title": "HLV Solskjaer lên tiếng về tương lai của Cavani", "des": "Thuyền trưởng Man Utd được yêu cầu nói về tương lai của Edinson Cavani trong buổi họp báo trước chuyến làm khách gặp Tottenham ngày 11/4.", "href": "/hlv-solskjaer-len-tieng-ve-tuong-lai-cua-cavani-post1202733.html"}
{"title": "Báo Trung Quốc lo ngại sức mạnh tuyển Philippines", "des": "Tuyển Philippines đang tích cực nhập tịch các cầu thủ chất lượng và đe dọa tới khả năng đi tiếp của Trung Quốc tại vòng loại World Cup.", "href": "/bao-trung-quoc-lo-ngai-suc-manh-tuyen-philippines-post1202623.html"}
{"title": "Dàn tiền vệ xuất sắc chưa xác định tương lai", "des": "Luka Modric và một loạt tiền vệ tên tuổi của bóng đá thế giới có thể ra đi tự do trong hè 2021.", "href": "/dan-tien-ve-xuat-sac-chua-xac-dinh-tuong-lai-post1202515.html"}
{"title": "Nỗi niềm phía sau sân cỏ của Jesse Lingard", "des": "Tiền vệ người Anh là trụ cột của gia đình khi vừa phải tập trung thi đấu, đồng thời gánh vác luôn nhiệm vụ chăm sóc các em và người mẹ bị trầm cảm.", "href": "/noi-niem-phia-sau-san-co-cua-jesse-lingard-post1202445.html"}
{"title": "'Văn Toàn ngày càng đáng sợ tại HAGL'", "des": "Nguyễn Văn Toàn đang thể hiện phong độ thuyết phục khi đóng góp 5 bàn cho HAGL sau 8 trận ở V.League 2021.", "href": "/van-toan-ngay-cang-dang-so-tai-hagl-post1202589.html"}
{"title": "Tỉnh Quảng Ninh lên tiếng về việc cầu thủ bị nợ lương", "des": "Đại diện tỉnh Quảng Ninh chia sẻ rằng ngân sách Nhà nước không thể được dùng để chi trả lương, thưởng cho các cầu thủ đội bóng.", "href": "/tinh-quang-ninh-len-tieng-ve-viec-cau-thu-bi-no-luong-post1202705.html"}
{"title": "Người tình hơn 6 tuổi của Mbappe", "des": "Truyền thông Italy tiết lộ tiền đạo 22 tuổi Kylian Mbappe đang hẹn hò với người mẫu Luisa Jacobelli.", "href": "/nguoi-tinh-hon-6-tuoi-cua-mbappe-post1202565.html"}
{"title": "CLB Sài Gòn chiêu mộ trung vệ người Senegal", "des": "Với Pape Diakite, huấn luyện viên Phùng Thanh Phương có một bản hợp đồng chất lượng để gia cố hàng thủ.", "href": "/clb-sai-gon-chieu-mo-trung-ve-nguoi-senegal-post1202692.html"}
{"title": "Công Phượng lùi lại và HAGL tiến lên", "des": "Quyền uy và tài năng của Kiatisuk đang thay đổi Công Phượng, thay đổi hàng thủ HAGL và biến đội bóng phố núi thành cỗ máy không thể ngăn chặn ở V.League 2021.", "href": "/cong-phuong-lui-lai-va-hagl-tien-len-post1202662.html"}
{"title": "Xuân Trường cười hạnh phúc bên vợ sắp cưới", "des": "Tiền vệ HAGL chụp selfie bức ảnh ngồi chung xe với Ngô Mai Nhuệ Giang trong buổi chiều 9/4.", "href": "/xuan-truong-cuoi-hanh-phuc-ben-vo-sap-cuoi-post1202690.html"}
{"title": "'Hành vi của Zeros là rất nghiêm trọng'", "des": "Ban tổ chức giải Liên Minh Huyền Thoại Việt Nam (VCS) đã cân nhắc kỹ càng trước khi đưa ra án cấm thi đấu vĩnh viễn dành cho tuyển thủ Phạm \"Zeros\" Minh Lộc.", "href": "/hanh-vi-cua-zeros-la-rat-nghiem-trong-post1202656.html"}
{"title": "CLB Quảng Ninh có thể mất hàng loạt tuyển thủ quốc gia và U22", "des": "Nếu không sớm giải quyết tình trạng nợ lương, thưởng, CLB Quảng Ninh đối mặt nguy cơ mất các trụ cột, trong đó có tuyển thủ quốc gia và U22.", "href": "/clb-quang-ninh-co-the-mat-hang-loat-tuyen-thu-quoc-gia-va-u22-post1202609.html"}
{"title": "Lindelof và pha kiến tạo để đời ở Man United", "des": "Trên sân Nuevo Los Carmenes của Granada, Victor Lindelof khiến tất cả nhắc tới mình với pha chuyền dài kiến tạo cho Marcus Rashford lập công.", "href": "/lindelof-va-pha-kien-tao-de-doi-o-man-united-post1202642.html"}
{"title": "Lời cảnh tỉnh cho SGP trước siêu kinh điển", "des": "Đội Saigon Phantom (SGP) khiến cổ động viên lo lắng khi thi đấu sa sút thời gian gần đây.", "href": "/loi-canh-tinh-cho-sgp-truoc-sieu-kinh-dien-post1202485.html"}
{"title": "Nỗi thất vọng của Messi tại El Clasico khi vắng Ronaldo", "des": "Lionel Messi đã không ghi bàn thắng nào tại El Clasico kể từ khi Cristiano Ronaldo chuyển sang thi đấu cho Juventus hè 2018.", "href": "/noi-that-vong-cua-messi-tai-el-clasico-khi-vang-ronaldo-post1202464.html"}
{"title": "Tuấn Anh dự đám hỏi của Xuân Trường", "des": "Sáng 9/4, Nguyễn Tuấn Anh là cầu thủ duy nhất của HAGL có mặt tại đám hỏi Lương Xuân Trường.", "href": "/tuan-anh-du-dam-hoi-cua-xuan-truong-post1202570.html"}
{"title": "Cầu thủ CLB Quảng Ninh đồng loạt đòi hủy hợp đồng", "des": "Phạm Nguyên Sa nhấn mạnh sức chịu đựng của cầu thủ CLB Quảng Ninh đến giới hạn, do đó tất cả cùng lên tiếng để đòi công bằng.", "href": "/cau-thu-clb-quang-ninh-dong-loat-doi-huy-hop-dong-post1202552.html"}
{"title": "HAGL thắng 3 trận sân khách liên tiếp sau 14 năm", "des": "Kết quả 2-0 trước CLB Đà Nẵng ở vòng 8 V.League 2021 tối 8/4 giúp HAGL tái lập thành tích thắng 3 trận sân khách liên tiếp ở mùa giải 2007.", "href": "/hagl-thang-3-tran-san-khach-lien-tiep-sau-14-nam-post1202440.html"}
{"title": "Mbappe quyết đến Real Madrid", "des": "Kylian Mbappe từ chối lời mời gia hạn hợp đồng của PSG để được gia nhập Real Madrid.", "href": "/mbappe-quyet-den-real-madrid-post1202527.html"}
{"title": "Đám hỏi Xuân Trường được tổ chức kín đáo ở Hà Nội", "des": "Sáng 9/4, gia đình Lương Xuân Trường đã làm thủ tục dạm ngõ nhà gái Ngô Mai Nhuệ Giang tại Hà Nội.", "href": "/dam-hoi-xuan-truong-duoc-to-chuc-kin-dao-o-ha-noi-post1202458.html"}
